// 1장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {bump:['ship','D']},
 {talk:'andy'},
 {talk:'ellie',wrong:true,shotChoice:'02-ellie-question'},
 {talk:'dejean',shotBefore:'03-bridge',shotTap:'03b-tap-word'},
 {talk:'finn',wrong:true},
 {check:()=>petOn()&&!npcAt(14,4),msg:'Finn follows and leaves the bridge'},
 {talk:'or'},
 {talk:'andy',shotBefore:'04-dark-engine-room'},
 {inspect:['ship',1,4],shot:'05-terminal'},
 {talk:'customs',shotBefore:'06-dock'},
 {talk:'gyvoy'},
 {talk:'lina'},
 {talk:'trader'},
 {talk:'gyvoy'},
 {check:()=>state.items.includes('연료통'),msg:'fuel for seeds'},
 {talk:'terence',shotBefore:'07-city'},
 {talk:'josias',wrong:true,shotBuild:'08-sentence-build'},
 {talk:'otylia'},
 {talk:'cafe',wrong:true},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'andy'},
 {check:()=>state.f.fixed,msg:'engine fixed'},
 {walkTo:['ship',8,13],then:'09-engine-room-lit'},
 {talk:'dejean'},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['ship',1,4]},
 {look:true,shot:'12-look'},
 {talklog:1,shot:'10a-talk-log'},
 {taps:1,shot:'10c-taps'},
 {panel:1,shot:'10-log'},
 {chapters:1,shot:'11-chapters'},
]
