// 2장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {bump:['lestari','A']},
 {talk:'basyl'},
 {talk:'uzoma',shotBefore:'02-cupola-gate'},
 {talk:'ellie'},
 {talk:'basyl',wrong:true,shotChoice:'03-basyl-question'},
 {talk:'tose1'},
 {talk:'grssia1'},
 {talk:'ichika1'},
 {talk:'finn'},
 {talk:'uzoma'},
 {check:()=>state.f.gift&&!state.items.includes('피의 병'),msg:'gift of passage fired into the Gate'},
 {talk:'dream',shotSay:{text:'방주 한 척이',name:'04-frame-dream'}},
 {check:()=>state.f.dream,msg:'interlude seen'},
 {inspect:['lestari',4,2]},
 {talk:'ellie',wrong:true},
 {check:()=>petOn()&&!npcAt(9,4),msg:'Ellie follows'},
 {walkTo:['lestari',8,7],then:'05-red-alert'},
 {talk:'tose1'},
 {talk:'finn',wrong:true,shotBuild:'06-beam-build'},
 {check:()=>state.f.beam,msg:'beam fired'},
 {talk:'uzoma'},
 {talk:'yoru',shotBefore:'07-five-dock'},
 {talk:'miteris'},
 {bump:['bubbletown','p']},
 {talk:'okimi',shotBefore:'08-bubbletown'},
 {talk:'resident'},
 {check:()=>state.items.includes('도시락'),msg:'lunch'},
 {talk:'yoru'},
 {check:()=>state.f.bubble,msg:'bubble finished'},
 {walkTo:['breakerville',20,13],then:'09-breakerville'},
 {talk:'davrux'},
 {talk:'tabia'},
 {talk:'guard',wrong:true},
 {talk:'dave'},
 {bump:['breakerville','H']},
 {talk:'davrux',wrong:true,shotBuild:'10-davrux-build'},
 {talk:'tabia'},
 {check:()=>state.f.contract,msg:'contract signed'},
 {talk:'dave',wrong:true},
 {talk:'dave2'},
 {talk:'tabia'},
 {check:()=>state.f.daves,msg:'Daves hired'},
 {talk:'keeper',wrong:true,shotBefore:'11-lodge-cafe'},
 {talk:'ichika'},{talk:'grssia'},{talk:'tose'},{talk:'basylB'},{talk:'finnB'},
 {talk:'davrux2',shotBefore:'12-wreck-entrance',shotSay:{text:'컨클루더 저격총',name:'13-rifle-cutscene'}},
 {check:()=>state.f.mapped&&state.items.includes('잔해 지도'),msg:'tunnels mapped'},
 {inspect:['wreck',22,2]},
 {walkTo:['wreck',8,4],then:'14-generator-room'},
 {bump:['breakerville','H']},
 {talk:'finnB',shotBefore:'15-night'},
 {check:()=>state.f.attack===1,msg:'attack started'},
 {talk:'grssia'},
 {talk:'ghost1',shotBefore:'16-ghost-attack'},
 {talk:'davrux2'},
 {talk:'finnW',shotBefore:'17-network-node'},
 {check:()=>state.f.attack===2,msg:'ghosts beaten'},
 {talk:'tose',shotSay:{text:'고스트 수류탄이',name:'18-tose-lie'}},
 {check:()=>state.f.lie,msg:'Toše lied'},
 {talk:'davrux2'},
 {talk:'grssia',wrong:true},
 {talk:'basylB',wrong:true,shotBefore:'19-bodies'},
 {talk:'dave'},{talk:'dave2'},{talk:'ghost2'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'davrux2'},
 {check:()=>state.f.dug,msg:'generator dug out'},
 {talk:'miterisB'},
 {talk:'finnW',shotBefore:'20-zpz-generator'},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['breakerville',8,13],shot:'21-terminal'},
 {panel:1,shot:'22-log'},
 {chapters:1,shot:'23-chapters'},
]
