// 3장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {bump:['ship','E']},
 {talk:'gyvoy'},
 {talk:'dejean',wrong:true,shotBefore:'02-bridge',shotChoice:'03-dejean-question'},
 {talk:'ellie',wrong:true},
 {talk:'finn',wrong:true,shotBefore:'04-owner-quarters'},
 {check:()=>petOn(),msg:'Finn follows'},
 {talk:'nglon',shotBefore:'05-sphere-one'},
 {talk:'pablo',wrong:true,shotBefore:'06-pablo'},
 {check:()=>state.f.filter,msg:'filter installed'},
 {talk:'renata'},
 {walkTo:['ship',6,12],then:'07a-cylinders'},
 {inspect:['ship',27,10],shot:'07-terminal'},
 // each ride (capsule, arrow train) narrates on arrival (zone greet), so walk one hop at a time and finish that line first
 {walkTo:['round',3,15]},{intro:1,shot:'08a-capsule-down'},
 {talk:'guard',shotBefore:'08-roundhouse'},
 {talk:'josias',wrong:true},
 {talk:'zelinda'},
 {talk:'mother',wrong:true,shotBefore:'09-marchioness'},
 {talk:'wynid',shotSay:{text:'곰팡이',name:'10-interlude-wynid'}},
 {walkTo:['round',20,13],then:'11-arboretum'},
 {walkTo:['hafnir',8,2]},{intro:1,shot:'12a-train-out'},
 {talk:'station',shotBefore:'12-hafnir-station'},
 {talk:'otylia',wrong:true,shotBuild:'13-otylia-build'},
 {talk:'vari',wrong:true,shotBefore:'14-variaka-call'},
 {talk:'laurella',wrong:true,shotBefore:'15-beach'},
 {talk:'dushan'},
 {talk:'terence'},
 {talk:'cafe',wrong:true},
 {walkTo:['round',24,15]},{intro:1},
 {walkTo:['ship',26,5]},{intro:1,shot:'16a-capsule-up'},
 {check:()=>!state.f.ride,msg:'the ride lines are done'},
 {talk:'dave1',shotBefore:'16-hangar-crates'},
 {talk:'dave2'},
 {talk:'gyvoy',wrong:true},
 {talk:'malvin',shotBuild:'17-malvin-build'},
 {walkTo:['ship',23,5],then:'18-zpz-installed'},
 {check:()=>!petOn(),msg:'Finn stops following at night'},
 {talk:'finn',wrong:true,shotBefore:'19-night'},
 {check:()=>state.badges.length===C.WORDS.length-1,msg:'15 words before the finale'},
 {talk:'dejean',shotSay:{text:'체렌코프',name:'20-epilogue'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'epi'},
 {clock:26*3600e3},
 {inspect:['ship',27,10]},
 {look:true,shot:'90-look'},
 {panel:1,shot:'21-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 // (the ship only: the airlock to Gondiar is locked from the night before departure on)
 {reviewTour:['ship'],carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:['ship']},
]
