// 4장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {talk:'pablo',shotBefore:'01b-pablo'},
 {talk:'dejean',shotBefore:'02-command-deck'},
 {talk:'uemi'},
 {talk:'woiykan',shotBefore:'03-woiykan'},
 {talk:'gyvoy'},
 {talk:'finn',wrong:true,shotChoice:'04-finn-question'},
 {check:()=>state.f.orbit&&!npcAt(13,5),msg:'Pablo opens the hangar door'},
 {inspect:['ship',4,1]},
 {talk:'ellieS',shotBefore:'05-hangar'},
 {talk:'binopal',wrong:true,shotBefore:'06-natt-hall'},
 {talk:'mique'},
 {talk:'cook',wrong:true,shotBefore:'07-canteen'},
 {bump:['natt','G']},
 {talk:'els',wrong:true},
 {check:()=>state.items.includes('우주복'),msg:'got a spacesuit'},
 {talk:'fomki'},
 {talk:'bensathN',shotBefore:'08-garage'},
 {talk:'ellieN'},
 {talk:'gyvoyN'},
 {inspect:['natt',9,5],shot:'09-terminal'},
 {talk:'pandiana',shotBefore:'10-hoodoo-garden'},
 {check:()=>state.f.breach&&!state.items.includes('핵 폭약'),msg:'wall breached'},
 {inspect:['plain',17,7]},
 {walkTo:['plain',15,9],then:'10b-dead-herd'},
 {walkTo:['plain',5,10],then:'10c-dust-ocean'},
 {inspect:['plain',12,12]},  // Ellie answers from inside the tank
 {talk:'miqueB',wrong:true,shotBefore:'11-trap-field'},
 {talk:'bensathB',shotSay:{text:'파도처럼',name:'12-saberstones'}},
 {check:()=>state.f.attack,msg:'the moat attack happened'},
 {talk:'miqueB'},
 {talk:'swarm',shotBefore:'13-moat-after'},
 {talk:'gyvoyB',wrong:true,shotBuild:'14-sentence-build'},
 {check:()=>state.f.causeway,msg:'causeway built'},
 {talk:'ellieB'},
 {talk:'elsB',shotBefore:'15-tank-buried'},
 {check:()=>state.f.bitten&&petOn(),msg:'Ellie follows'},
 {walkTo:['bk37',11,13],then:'15b-causeway'},
 {talk:'dave1',shotBefore:'16-stair-base'},
 {talk:'dave2'},
 {walkTo:['tower',13,11],then:'17-ghost-chase'},
 {talk:'gyvoyT'},
 {check:()=>state.f.mined,msg:'mines laid'},
 {talk:'mummyA',shotBefore:'18-hangar'},
 {talk:'finnB'},
 {walkTo:['tower',9,6],then:'19-hangar-lit'},
 {talk:'elsT'},
 {talk:'ghost1'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'finnB'},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['natt',9,5]},
 {look:true,shot:'90-look'},
 {panel:1,shot:'20-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
