// 5장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {talk:'lucia',wrong:true,shotBefore:'02-hq'},
 {check:()=>!!C.NPC.luciaCell.walk,msg:'루치아 walks to the interrogation room'},
 {pause:0,shot:'02a-lucia-walks'},
 {pause:3500},
 {check:()=>!C.NPC.luciaCell.walk,msg:'…and arrives'},
 {talk:'bopbe',wrong:true,shotBefore:'03-monitor-room',shotSay:{text:'봅베의 몸에서 불이',name:'04-bopbe-fire'}},
 {check:()=>state.f.bopbeDead&&!state.badges.includes('처형'),msg:'Bopbe burned; lab next'},
 {talk:'lucia'},
 {talk:'lab',shotChoice:'05-lab-question'},
 {check:()=>state.items.includes('오더바이저 가면'),msg:'othervisor mask'},
 {talk:'news',shotBefore:'06-news'},
 {bump:['city','G']},
 {talk:'zikar',wrong:true,shotBefore:'07-street'},
 {talk:'snatch',shotBefore:'08-disguised'},
 {check:()=>state.f.sting&&!state.items.includes('오더바이저 가면'),msg:'sting done, mask used'},
 {talk:'zikar'},
 {check:()=>state.items.includes('표적 드론 설계도'),msg:'drone blueprint clue'},
 {talk:'news'},
 {talk:'aljan'},
 {talk:'pro2'},
 {talk:'vanilda',shotBuild:'09-sentence-build'},
 {check:()=>!npcAt(13,11)&&!npcAt(14,11),msg:'protest line opens'},
 {talk:'bersche'},
 {talk:'news'},
 {talk:'feed'},
 {talk:'tose',shotBefore:'10-lucia-feed'},
 {talk:'cleaner'},
 {walkTo:['tower',12,11],then:'11-capsule-window'},
 {talk:'feed',shotSay:{text:'사무실 창문',name:'12-office-blast'}},
 {check:()=>state.f.boom,msg:'capsule bomb'},
 {talk:'maria'},
 {talk:'news'},
 {talk:'jimena',shotBefore:'13-memorial'},
 {talk:'zelinda'},
 {talk:'medusaSt',shotBefore:'14-medusa'},
 {talk:'medusa',wrong:true},
 {talk:'lab'},
 {check:()=>state.f.liliana&&state.items.includes('캡슐 역 영상'),msg:'Liliana identified'},
 {talk:'makaio',shotBefore:'15-balcony',shotSay:{text:'말을 못 해요',name:'16-sniped'}},
 {talk:'barman',wrong:true,shotBefore:'17-bar'},
 {talk:'spirit'},
 {check:()=>state.f.occupied,msg:'two years later: occupation'},
 {talk:'news'},
 {talk:'general',shotBefore:'18-occupation'},
 {talk:'ghost1'},
 {talk:'lion1'},
 {talk:'news'},
 {talk:'news'},
 {check:()=>state.f.missile,msg:'missile news'},
 {talk:'maria'},
 {talk:'otylia',shotBefore:'19-villa'},
 {talk:'zelindaS'},
 {talk:'haian'},
 {talk:'aljanS'},
 {check:()=>state.f.club,msg:'club opens'},
 {talk:'news'},
 {talk:'patch',shotBefore:'20-club'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'jimenaC',shotSay:{text:'기보이 엔포',name:'21-gyvoy'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['hq',1,2],shot:'22-terminal'},
 {look:true,shot:'90-look'},
 {panel:1,shot:'23-log'},
 {chapters:1,shot:'24-chapters'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
