// 5장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {talk:'lucia',wrong:true,shotBefore:'02-hq'},
 {talk:'bopbe',wrong:true,shotBefore:'03-interview',shotSay:{text:'봅베의 몸에서 불이',name:'04-bopbe-fire'}},
 {check:()=>state.f.bopbeDead&&!state.badges.includes('처형'),msg:'Bopbe burned; lab next'},
 {talk:'lab',shotChoice:'05-lab-question'},
 {check:()=>state.items.includes('오더바이저 가면'),msg:'othervisor mask'},
 {talk:'news',shotBefore:'06-news'},
 {bump:['city','G']},
 {talk:'zikar',wrong:true,shotBefore:'07-street'},
 {talk:'snatch'},
 {check:()=>state.f.sting&&!state.items.includes('오더바이저 가면'),msg:'sting done, mask used'},
 {talk:'zikar'},
 {check:()=>state.items.includes('표적 드론 설계도'),msg:'drone blueprint clue'},
 {talk:'news'},
 {talk:'aljan'},
 {talk:'pro2'},
 {talk:'vanilda',shotBuild:'08-sentence-build'},
 {check:()=>!npcAt(13,11)&&!npcAt(14,11),msg:'protest line opens'},
 {talk:'bersche'},
 {talk:'news'},
 {talk:'tose',shotBefore:'09-high-rosa'},
 {talk:'luciaT'},
 {talk:'cleaner',shotSay:{text:'소리는 안 들려요',name:'10-explosion'}},
 {walkTo:['tower',12,11],then:'11-capsule-window'},
 {talk:'dock'},
 {talk:'news'},
 {talk:'jimena',shotBefore:'12-memorial'},
 {talk:'zelinda'},
 {talk:'maria'},
 {talk:'medusaSt',shotBefore:'13-medusa'},
 {talk:'medusa',wrong:true},
 {talk:'lab'},
 {check:()=>state.f.liliana&&state.items.includes('캡슐 역 영상'),msg:'Liliana identified'},
 {talk:'makaio',shotBefore:'14-balcony',shotSay:{text:'쓰러져요',name:'15-sniped'}},
 {talk:'barman',wrong:true,shotBefore:'16-bar'},
 {talk:'spirit'},
 {check:()=>state.f.occupied,msg:'two years later: occupation'},
 {talk:'news'},
 {talk:'general',shotBefore:'17-occupation'},
 {talk:'ghost1'},
 {talk:'lion1'},
 {talk:'news'},
 {talk:'news'},
 {check:()=>state.f.missile,msg:'missile news'},
 {talk:'maria'},
 {talk:'otylia',shotBefore:'18-safehouse'},
 {talk:'zelindaS'},
 {talk:'aljanS'},
 {check:()=>state.f.club,msg:'club opens'},
 {talk:'patch',shotBefore:'19-club'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'jimenaC',shotSay:{text:'기보이 엔포',name:'20-gyvoy'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['hq',1,2],shot:'21-terminal'},
 {panel:1,shot:'22-log'},
 {chapters:1,shot:'23-chapters'},
]
