// 6장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {bump:['ship','D']},
 {talk:'dejean'},
 {talk:'ellieS'},
 {talk:'uemi',wrong:true,shotChoice:'02-uemi-question',shotBuild:'03-build-layers'},
 {check:()=>state.f.briefed,msg:'briefed, shuttle open'},
 {inspect:['ship',6,2],shot:'04-kingsnest-screen'},
 {talk:'gyM',shotBefore:'05-mytalport'},
 {check:()=>state.items.includes('거래 물건 상자'),msg:'trade box from Gyvoy'},
 {bump:['mytal','r']},
 {talk:'finnSick',wrong:true},
 {check:()=>petOn(),msg:'Finn follows'},
 {talk:'koaM'},
 {talk:'kech'},
 {talk:'nievas'},
 {inspect:['mytal',4,4]},
 {talk:'dylan'},
 {check:()=>state.f.ride,msg:'ride to Nassau'},
 {talk:'jazon'},
 {talk:'ettan',shotBefore:'06-nassau'},
 {check:()=>state.f.ettanOut,msg:'Ettan walked out'},
 {talk:'jazon',wrong:true,shotBuild:'07-haggle-build'},
 {check:()=>state.f.hired&&!state.items.includes('거래 물건 상자'),msg:'airboat hired for the box'},
 {talk:'cafe',wrong:true},
 {inspect:['nassau',13,10],shot:'08-honey-hub'},
 {bump:['boat','r']},
 {talk:'ayden',shotBefore:'09-airboat'},
 {talk:'ellieB'},
 {talk:'jazonB'},
 {talk:'rylee'},
 {check:()=>state.items.includes('케스카 구이'),msg:'roast kescaw'},
 {talk:'koaB'},
 {talk:'kaizenB'},
 {talk:'uemiB'},
 {check:()=>state.f.found,msg:'factory found'},
 {talk:'bensath',shotBefore:'10-factory-mouth'},
 {talk:'gyF'},
 {talk:'elsbeth',shotBefore:'11-speck-chamber'},
 {talk:'gyF',shotBefore:'12-assembly-hall'},
 {check:()=>!petOn(),msg:'Finn goes to the bulb'},
 {talk:'finnBulb'},
 {check:()=>state.f.os&&petOn(),msg:'OS absorbed, Finn follows again'},
 {talk:'dave1'},
 {talk:'koaF',shotBefore:'13-web-grozlamia'},
 {check:()=>state.f.ambush,msg:'ambush happened'},
 {talk:'ellieF',wrong:true,shotBefore:'14-after-ambush'},
 {talk:'nweid',shotBuild:'15-nightweid-build'},
 {check:()=>state.f.massacre,msg:'pirates destroyed'},
 {talk:'dave2'},
 {talk:'kaizenF'},
 {inspect:['factory',13,15]},
 {talk:'jazonB',shotBefore:'16-boat-after'},
 {talk:'dylanB'},
 {talk:'ellieB'},
 {check:()=>state.f.argue,msg:'Ellie snaps at Finn'},
 {talk:'ellieS',shotBefore:'17-home-screen'},
 {talk:'gyShip'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'otylia',shotSay:{text:'엉망',name:'18-otylia-call'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['boat',8,11],shot:'19-terminal'},
 {look:true,shot:'90-look'},
 {panel:1,shot:'20-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
