// 7장 walkthrough: order a player would follow. wrong:true answers one question wrong first.
[
 {intro:1,shot:'01-intro'},
 {bump:['ship','R']},
 {talk:'finn'},
 {talk:'gath'},
 {talk:'otylia',wrong:true,shotChoice:'02-otylia-question'},
 {talk:'laurella'},
 {inspect:['ship',8,1],shot:'03-news'},
 {talk:'zelinda',wrong:true},
 {talk:'everett',shotBefore:'04-quarters'},
 {check:()=>state.f.plan,msg:'plan made'},
 {talk:'holo1',shotSay:{text:'진짜 기보이',name:'05-interlude-terence'}},
 {talk:'ellie'},
 {talk:'pablo'},
 {talk:'aljan',wrong:true},
 {talk:'dejean',shotBefore:'06-hangar'},
 {check:()=>state.items.includes('우주복'),msg:'got the suit'},
 {talk:'gyvoy'},
 {talk:'bensath'},
 {talk:'daveS'},
 {talk:'finn'},
 {check:()=>state.f.launch,msg:'launched'},
 {walkTo:['dolod',5,6],then:'07-dolod-hangar'},
 {talk:'finnD'},
 {talk:'dave1',wrong:true},
 {talk:'dave2'},
 {talk:'gyvoyD'},
 {talk:'bensathD',shotBefore:'08-storm-gallery'},
 {talk:'finnD',shotBefore:'09-petal-chamber'},
 {check:()=>state.f.linked,msg:'Finn linked to the Engine'},
 {talk:'holo2',shotSay:{text:'다곤',name:'10-interlude-thyra'}},
 {talk:'finnD'},
 {talk:'dave2',wrong:true,shotBefore:'11-stranded'},
 {check:()=>state.items.includes('물병'),msg:'water for Finn'},
 {talk:'finnD',shotBuild:'12-build'},
 {check:()=>state.f.woke&&!state.items.includes('물병'),msg:'Finn awake'},
 {walkTo:['dolod',22,15],then:'13-anchor-hangar'},
 {walkTo:['ship',22,14],then:'14-ship-accel'},
 {talk:'ellie'},
 {talk:'pablo',wrong:true},
 {talk:'ellie',wrong:true,shotSay:{text:'안녕~',name:'15-memory'}},
 {check:()=>state.items.includes('레콜 병'),msg:'rekaul vial'},
 {talk:'aljan'},
 {check:()=>!state.items.includes('레콜 병'),msg:'vial handed in'},
 {check:()=>state.badges.length===C.WORDS.length,msg:'all words collected'},
 {talk:'dejean',shotBefore:'16-command'},
 {check:()=>state.f.jump,msg:'10,000 g jump'},
 {walkTo:['capo',11,8],then:'17-capo-gate'},
 {talk:'zelindaC'},
 {talk:'finnC'},
 {talk:'ellieC'},
 {talk:'dejeanC'},
 {talk:'holo3'},
 {talk:'holo3',shotSay:{text:'하나 끝',name:'18-empress'}},
 {talk:'zelindaC',shotSay:{text:'폭탄',name:'19-finale'}},
 {check:()=>state.f.done,msg:'chapter done'},
 {clock:26*3600e3},
 {inspect:['ship',1,4],shot:'20-terminal'},
 {talk:'zelindaC'},
 {look:true,shot:'90-look'},
 {panel:1,shot:'21-log'},
 // in-character review: with every word due, earlier chapters too, everyone who has a line asks it in their own voice, and it grades
 {reviewTour:Object.keys(C.ZONES),carry:1},
 // …and with nothing due, people with a line you haven't heard say it as plain talk (the word filled in, ungraded)
 {hearTour:Object.keys(C.ZONES)},
]
