/* Settings for the shared engine (walk-engine): this game's names, storage prefix and default player. */
var GAME={prefix:'seongsilho',title:'성실호',log:'항해 일지',
 term:{allWords:n=>[`단어 ${n}개를 다 모았어요!`,'복습할수록 ★가 늘어나요. 사람들도, 신호 단말기도 물어봐요.'],carry:'지난 항해에서 배운 말도 다시 나와요.',wrap:'이번 장에서 배운 말, 한 번 더 떠올려요.',name:'신호 단말기',empty:'신호 없음. 아직 일지가 비어 있어요.',idle:'새 신호가 없어요.',next:'다음 신호',due:(n,k)=>`신호가 왔어요. 단어 ${n}개가 기다려요.`+(k<n?` 이번에는 ${k}개만 해요.`:''),end:'신호 끝. 다음에 또 와요.'},

 /* spaced review: due again after 2 story beats or 5 minutes, then 5 beats or 20 minutes; later levels are hours and days, and one
    shared record lets later chapters bring earlier words back (people's lines, the 신호 단말기 and the last round of each chapter) */
 srs:{start:1,gap:[0,5*60e3,20*60e3,4*3600e3,24*3600e3,3*24*3600e3],beats:[0,2,5],shared:1},
 /* the crew look (walk-engine crew style): 성실호's people in everyday kit instead of 방과 후's school uniforms; per character from a
    book audit (2026-10-09: clothes, jaw, eye colour where the book gives one, 조사이어스's beard, 그르시아's visor, a few colour fixes) */
 lookStyle:'crew',
 looks:{'엘리':{"kit":{"vest":"#8A6A4A","pouches":"#6E7B5A"},"jaw":"pointed"},
 '드장 선장':{"uniform":1,"onePiece":1,"shirt":"#3B3F8A","pants":"#4A3A7A","cap":null},
 '핀':{"kit":{"sweater":"#B59A62","coat":"#5E4A6E"}},
 '오르':{"kit":{"vest":"#8A6A4A","pouches":"#6E7B5A"}},
 '옥테인 기관장':{"kit":{"pouches":"#9A4A3A","vest":"#4A5A6E"}},
 '기보이':{"kit":{"coat":"#B59A62","vest":"#5E4A6E"}},
 '천문학자 리나':{"kit":{"coat":"#8A6A4A","pouches":"#6E7B5A"}},
 '광부':{"kit":{"pouches":"#9A4A3A","strap":"#4A5A6E"}},
 '테렌스 형사':{"kit":{"coat":"#B59A62","pouches":"#5E4A6E"}},
 '조사이어스':{"kit":{"coat":"#8A6A4A","vest":"#6E7B5A"},"eye":"#7F95A8","fullBeard":1},
 '오틸리아':{"kit":{"sweater":"#9A4A3A","strap":"#4A5A6E"}},
 '카페 사장님':{"kit":{"sweater":"#B59A62","vest":"#5E4A6E"}},
 '우조마 선장':{"kit":{"pouches":"#8A6A4A","strap":"#6E7B5A"},"jaw":"round"},
 '베이질 목사':{"kit":{"coat":"#9A4A3A","pouches":"#4A5A6E"},"jaw":"round"},
 '그르시아':{"kit":{"pouches":"#B59A62","strap":"#5E4A6E"},"visor":1},
 '이치카':{"kit":{"pouches":"#8A6A4A","strap":"#6E7B5A"}},
 '요루':{"kit":{"pouches":"#9A4A3A","strap":"#4A5A6E"}},
 '미테리스':{"kit":{"vest":"#B59A62","strap":"#5E4A6E"}},
 '오키미살':{"kit":{"pouches":"#8A6A4A","vest":"#6E7B5A"}},
 '버블타운 주민':{"kit":{"sweater":"#9A4A3A","vest":"#4A5A6E"}},
 '타비아':{"kit":{"pouches":"#B59A62","strap":"#5E4A6E"}},
 '로지 주인':{"kit":{"sweater":"#8A6A4A","vest":"#6E7B5A"}},
 '맬빈 기관장':{"kit":{"pouches":"#9A4A3A","strap":"#4A5A6E"}},
 '응글론':{"kit":{"vest":"#B59A62","pouches":"#5E4A6E"}},
 '경비원':{"uniform":1,"onePiece":1},
 '젤린다':{"kit":{"coat":"#9A4A3A","vest":"#4A5A6E"},"jaw":"pointed"},
 '역무원':{"uniform":1,"onePiece":1},
 '테렌스':{"kit":{"coat":"#8A6A4A","pouches":"#6E7B5A"}},
 '해변 카페 사장님':{"kit":{"sweater":"#9A4A3A","pouches":"#4A5A6E"}},
 '우에미주발리':{"kit":{"vest":"#B59A62","strap":"#5E4A6E"}},
 '비노팔':{"kit":{"vest":"#8A6A4A","pouches":"#6E7B5A"}},
 '미크 오독스':{"kit":{"pouches":"#9A4A3A","strap":"#4A5A6E"}},
 '나트 식당 아저씨':{"kit":{"sweater":"#B59A62","vest":"#5E4A6E"}},
 '엘스베스':{"kit":{"pouches":"#8A6A4A","vest":"#6E7B5A"},"eye":"#BFC5CA"},
 '폼키':{"uniform":1,"onePiece":1},
 '벤사스 하사':{"uniform":1,"onePiece":1},
 '판디아나':{"uniform":1,"onePiece":1},
 '에두살':{"uniform":1,"onePiece":1},
 '루치아':{"kit":{"vest":"#B59A62","pouches":"#5E4A6E"}},
 '봅베':{"kit":{"sweater":"#8A6A4A","strap":"#6E7B5A"},"jaw":"round"},
 '감식 요원':{"kit":{"coat":"#9A4A3A","pouches":"#4A5A6E"}},
 '마리아 호세 서장':{"uniform":1,"shirt":"#2F6B4A","pants":"#E4E2D8","cap":"#9A5A9A"},
 '베르셰':{"kit":{"vest":"#8A6A4A","strap":"#6E7B5A"}},
 '메두사':{"kit":{"vest":"#9A4A3A","strap":"#4A5A6E"}},
 '지카르 타소트':{"kit":{"sweater":"#B59A62","pouches":"#5E4A6E"}},
 '납치범':{"kit":{"coat":"#8A6A4A","strap":"#6E7B5A"},"jaw":"round"},
 '알잔':{"kit":{"sweater":"#9A4A3A","strap":"#4A5A6E"}},
 '바닐다':{"kit":{"vest":"#B59A62","strap":"#5E4A6E"}},
 '히메나':{"kit":{"sweater":"#8A6A4A","strap":"#6E7B5A"}},
 '하이안':{"kit":{"sweater":"#9A4A3A","vest":"#4A5A6E"},"hair":"#9A9A9A","hairHi":"#BDBDBD"},
 '바텐더':{"kit":{"vest":"#B59A62","sweater":"#5E4A6E"}},
 '오틸리아 (화면)':{"kit":{"sweater":"#8A6A4A","strap":"#6E7B5A"}},
 '에이든':{"kit":{"pouches":"#9A4A3A","strap":"#4A5A6E"}},
 '로렐라':{"kit":{"sweater":"#B59A62","strap":"#5E4A6E"}},
 '에버렛':{"kit":{"coat":"#8A6A4A","vest":"#6E7B5A"}},
 '알잔 선생님':{"kit":{"coat":"#9A4A3A","pouches":"#4A5A6E"}}},
 player:{hair:'#2A2F4A',skin:'#F1C9A5',shirt:'#E4E1D6',pants:'#3B4650',belt:'#E8962A'}};
